
function makeButtons(){
	var navMenu = $('#RecruitProfileNav .ProfileNav');
	if( navMenu.length == 0){
		return false;
	}

	var strHtml = '<ul class="level1 static" role="menu" style="position: absolute; right: 0px;">';
		strHtml += '<li role="menuitem" class="static" style="position: relative;">';
			strHtml += '<a class="level1 static" id="btnSetRate" href="#">Max Toggle</a>';
		strHtml += '</li>';
		strHtml += '<li role="menuitem" class="static" style="position: relative;">';
			strHtml += '<a class="level1 static" href="#" id="btnSetSettings">Settings</a>';
		strHtml += '</li>';
	strHtml += '</ul>';
	navMenu.eq(0).append(strHtml);
	
	var strScript = '';

	strScript += 'function setCookie(cname, cvalue, exdays) {\n';
		strScript += 'var d = new Date();\n';
		strScript += 'd.setTime(d.getTime() + (exdays*24*60*60*1000));\n';
		strScript += 'var expires = "expires="+ d.toUTCString();\n';
		strScript += 'document.cookie = cname + "=" + cvalue + ";" + expires + ";path=/";\n';
	strScript += '}\n';
	strScript += 'function getCookie(cname) {\n';
		strScript += 'var name = cname + "=";\n';
		strScript += 'var decodedCookie = decodeURIComponent(document.cookie);\n';
		strScript += 'var ca = decodedCookie.split(";");\n';
		strScript += 'for(var i = 0; i <ca.length; i++) {\n';
			strScript += 'var c = ca[i];\n';
			strScript += 'while (c.charAt(0) == " ") {\n';
				strScript += 'c = c.substring(1);\n';
			strScript += '}\n';
			strScript += 'if (c.indexOf(name) == 0) {\n';
				strScript += 'return c.substring(name.length, c.length);\n';
			strScript += '}\n';
		strScript += '}\n';
		strScript += 'return "";\n';
	strScript += '}\n';
	strScript += 'var g_nPotentialVeryLow = 0;\n';
	strScript += 'var g_nPotentialLow = 4;\n';
	strScript += 'var g_nPotentialModerate = 10;\n';
	strScript += 'var g_nPotentialHigh = 20;\n';
	strScript += 'var g_nPotentialVeryHigh = 30;\n';
	strScript += 'var g_bToggled = false;\n';

	strScript += 'if(getCookie("g_nPotentialVeryLow") == ""){\n';
		strScript += 'setCookie("g_nPotentialVeryLow", g_nPotentialVeryLow, 365);\n';
	strScript += '} else{\n';
		strScript += 'g_nPotentialVeryLow = getCookie("g_nPotentialVeryLow")*1;\n';
	strScript += '}\n';
	strScript += 'if(getCookie("g_nPotentialLow") == ""){\n';
		strScript += 'setCookie("g_nPotentialLow", g_nPotentialLow, 365);\n';
	strScript += '} else{\n';
		strScript += 'g_nPotentialLow = getCookie("g_nPotentialLow")*1;\n';
	strScript += '}\n';
	strScript += 'if(getCookie("g_nPotentialModerate") == ""){\n';
		strScript += 'setCookie("g_nPotentialModerate", g_nPotentialModerate, 365);\n';
	strScript += '} else{\n';
		strScript += 'g_nPotentialModerate = getCookie("g_nPotentialModerate")*1;\n';
	strScript += '}\n';
	strScript += 'if(getCookie("g_nPotentialHigh") == ""){\n';
		strScript += 'setCookie("g_nPotentialHigh", g_nPotentialHigh, 365);\n';
	strScript += '} else{\n';
		strScript += 'g_nPotentialHigh = getCookie("g_nPotentialHigh")*1;\n';
	strScript += '}\n';
	strScript += 'if(getCookie("g_nPotentialVeryHigh") == ""){\n';
		strScript += 'setCookie("g_nPotentialVeryHigh", g_nPotentialVeryHigh, 365);\n';
	strScript += '} else{\n';
		strScript += 'g_nPotentialVeryHigh = getCookie("g_nPotentialVeryHigh")*1;\n';
	strScript += '}\n';

	strScript += "function setRate(){\n";
		strScript += "var tables = $('.ratingsTable .recruitRatings');\n";
		strScript += "if(tables.length == 0)return false;\n";
		strScript += "if(tables.eq(0).is(':hidden'))return false;\n";
		strScript += "var trs = tables.eq(0).find('tr');\n";
		strScript += "var totalRates = 0\n;"
		strScript += "for( var i = 0; i < trs.length; i++){\n";
			strScript += "var curTr = trs.eq(i);\n";
			strScript += "var rating = curTr.find('.rating span').eq(0);\n";
			strScript += "if(curTr.find('.name').eq(0).text().toLowerCase() == 'work ethic'){\n";
				strScript += "totalRates += parseInt(rating.text());\n";
				strScript += "continue;\n";
			strScript += "}\n";
			strScript += "var preClassName = rating.attr('preClass');\n";
			strScript += "var className = rating.attr('class').split(' ')[0];\n";
			strScript += "var rates = rating.text();\n";
			strScript += "if( parseInt(rates)){\n";
				strScript += "var nRate = rates * 1;\n";
				strScript += "var nRaisingValue = 0;\n";
				strScript += "var switchString = className;\n";
				strScript += "if(g_bToggled){\n";
					strScript += "switchString = preClassName;\n";
				strScript += "}\n";
				strScript += "switch(switchString){\n";
					strScript += "case 'potential_verylow':\n";
					strScript += "nRaisingValue = g_nPotentialVeryLow;\n";
					strScript += "break;\n";
					strScript += "case 'potential_low':\n";
					strScript += "nRaisingValue = g_nPotentialLow;\n";
					strScript += "break;\n";
					strScript += "case 'potential_average':\n";
					strScript += "nRaisingValue = g_nPotentialModerate;\n";
					strScript += "break;\n";
					strScript += "case 'potential_high':\n";
					strScript += "nRaisingValue = g_nPotentialHigh;\n";
					strScript += "break;\n";
					strScript += "case 'potential_veryhigh':\n";
					strScript += "nRaisingValue = g_nPotentialVeryHigh;\n";
					strScript += "break;\n";
				strScript += "}\n";
				strScript += "if(!g_bToggled){\n";
					strScript += "rating.attr('preClass', className);\n";
					strScript += "rating.attr('class', 'potential_verylow');\n";
					strScript += "nRate += nRaisingValue;\n";
				strScript += "} else{\n";
					strScript += "nRate -= nRaisingValue;\n";
					strScript += "rating.attr('class', preClassName);\n";
					strScript += "rating.attr('preClass', '');\n";
				strScript += "}\n";
				strScript += "nRate = (nRate >= 100 ? 100 : nRate);\n";
				strScript += "rating.html(nRate);\n";
				strScript += "curTr.find('.ratingbar_section span').eq(0).css('width', 'calc('+nRate+'% - 2px)');\n";
				strScript += "totalRates += nRate;\n";
			strScript += "}\n";
		strScript += "}\n";
		strScript += "g_bToggled = !g_bToggled;\n";
		strScript += "$('.recruitRating').text(totalRates);\n";
	strScript += "}\n";

	strScript += "function CloseSettings(){\n";
		strScript += "$('.RecruitRatingsContainer').show();\n";
		strScript += "$('.settingsPage').hide();\n";
	strScript += "}\n";

	strScript += "function SavePotential(){\n";
		strScript += "g_nPotentialVeryLow = $('input[name=" + '"VeryLow"]' + "').val() * 1;\n";
		strScript += "g_nPotentialLow = $('input[name=" + '"Low"]' + "').val() * 1;\n";
		strScript += "g_nPotentialModerate = $('input[name=" + '"Moderate"]' + "').val() * 1;\n";
		strScript += "g_nPotentialHigh = $('input[name=" + '"High"]' + "').val() * 1;\n";
		strScript += "g_nPotentialVeryHigh = $('input[name=" + '"VeryHigh"]' + "').val() * 1;\n";
		strScript += "setCookie('g_nPotentialVeryLow',g_nPotentialVeryLow,365);\n";
		strScript += "setCookie('g_nPotentialLow',g_nPotentialLow,365);\n";
		strScript += "setCookie('g_nPotentialModerate',g_nPotentialModerate,365);\n";
		strScript += "setCookie('g_nPotentialHigh',g_nPotentialHigh,365);\n";
		strScript += "setCookie('g_nPotentialVeryHigh',g_nPotentialVeryHigh,365);\n";
		strScript += "CloseSettings();\n";
	strScript += "}\n";

	strScript += "function setSettings(){\n";
		strScript += "if($('.settingsPage').length == 0){\n";
			strScript += "strHtml = '';\n";
			strScript += "strHtml += '<div class=" + '"settingsPage"' + " style=" + '"background-color:#eeeff1;padding:10px;"' + ">';\n";
				strScript += "strHtml += '<div onclick=" + '"CloseSettings()"' + " style=" + '"font-size:1.5em;font-weight:bold;float:right;cursor:pointer;"' + ">X</div>';\n";
				strScript += "strHtml += '<table style=" + '"margin:auto; font-size:1.5em; font-weight:bold;"' + ">';\n";
					strScript += "strHtml += '<tr>';\n";
						strScript += "strHtml += '<td style=" + '"padding:10px;"' + ">Value to add for Petential Very Low:</td>';\n";
						strScript += "strHtml += '<td style=" + '"padding:10px;"' + "><input type=" + '"text"' + " name=" + '"VeryLow"' + "></td>';\n";
					strScript += "strHtml += '</tr>';\n";
					strScript += "strHtml += '<tr>';\n";
						strScript += "strHtml += '<td style=" + '"padding:10px;"' + ">Value to add for Petential Low:</td>';\n";
						strScript += "strHtml += '<td style=" + '"padding:10px;"' + "><input type=" + '"text"' + " name=" + '"Low"' + "></td>';\n";
					strScript += "strHtml += '</tr>';\n";
					strScript += "strHtml += '<tr>';\n";
						strScript += "strHtml += '<td style=" + '"padding:10px;"' + ">Value to add for Petential Moderate:</td>';\n";
						strScript += "strHtml += '<td style=" + '"padding:10px;"' + "><input type=" + '"text"' + " name=" + '"Moderate"' + "></td>';\n";
					strScript += "strHtml += '</tr>';\n";
					strScript += "strHtml += '<tr>';\n";
						strScript += "strHtml += '<td style=" + '"padding:10px;"' + ">Value to add for Petential High:</td>';\n";
						strScript += "strHtml += '<td style=" + '"padding:10px;"' + "><input type=" + '"text"' + " name=" + '"High"' + "></td>';\n";
					strScript += "strHtml += '</tr>';\n";
					strScript += "strHtml += '<tr>';\n";
						strScript += "strHtml += '<td style=" + '"padding:10px;"' + ">Value to add for Petential Very High:</td>';\n";
						strScript += "strHtml += '<td style=" + '"padding:10px;"' + "><input type=" + '"text"' + " name=" + '"VeryHigh"' + "></td>';\n";
					strScript += "strHtml += '</tr>';\n";
				strScript += "strHtml += '</table>';\n";
				strScript += "strHtml += '<div onclick=" + '"SavePotential()"' + " style=" + '"margin: auto; width: 3em; font-size: 1.4em; font-weight: bold; cursor: pointer; border: 1px solid; text-align: center; color: gray;padding:5px 10px 5px 10px;"' + ">Save</div>';\n";
				strScript += "strHtml += '<p style=" + '"text-align:center; font-size:1.3em;"' + ">If you find this extension useful, please consider donating.</p>';\n";
				strScript += "strHtml += '<p style=" + '"text-align:center; font-size:1.3em;"' + ">Donations will help with improvements and new features.</p>';\n";
				strScript += "strHtml += '<p style=" + '"text-align:center;"' + "><a href=" + '"https://www.paypal.me/milkywayco" target="_blank" style="text-align:center;"' + ">Paypal.me</a></p>';\n";
			strScript += "strHtml += '</div>';\n";
			strScript += "$('.RecruitProfile_TabBox').append(strHtml);\n";
		strScript += "} else{\n";
			strScript += "$('.settingsPage').show();\n";
		strScript += "}\n";
		strScript += "$('input[name=" + '"VeryLow"]' + "').val(g_nPotentialVeryLow);\n";
		strScript += "$('input[name=" + '"Low"]' + "').val(g_nPotentialLow);\n";
		strScript += "$('input[name=" + '"Moderate"]' + "').val(g_nPotentialModerate);\n";
		strScript += "$('input[name=" + '"High"]' + "').val(g_nPotentialHigh);\n";
		strScript += "$('input[name=" + '"VeryHigh"]' + "').val(g_nPotentialVeryHigh);\n";
		strScript += "$('.RecruitRatingsContainer').hide();\n";
	strScript += "}\n";
	
	strScript += 'document.getElementById("btnSetRate").addEventListener("click", function(){\n';
		strScript += 'setRate();\n';
	strScript += '});\n';
	
	strScript += 'document.getElementById("btnSetSettings").addEventListener("click", function(){\n';
		strScript += 'setSettings();\n';
	strScript += '});\n';

	var s = document.createElement("script");
	s.type = "text/javascript";
	s.text = strScript;
	document.body.appendChild( s );
	return true;
}
var interval = setInterval(function(){
	if(makeButtons() == true){
		clearInterval(interval);
	}
});
